---
- include_vars: java-machineagent-vars.yml

- name: Create a directory if it does not exist
  file:
    path: "{{ binary_path }}"
    state: directory
    owner: tomcat
    group: tomcat
    mode: '0777'
  become: true

- name: tar extract app agent binaries
  unarchive:
    src: "/home/tomcat/{{ zip_file }}"
    dest: "{{ binary_path }}"
    remote_src: yes

- name: Template config file to install folder
  template:
    src: "{{ controller_xml }}.j2"
    dest: "{{ binary_path }}/conf/{{ controller_xml }}"
    owner: tomcat
    group: tomcat
    mode: '0777'

- name: Template service file to systemd folder
  template:
    src: "{{ machineagent_systemd }}.service.j2"
    dest: "/etc/systemd/system/{{ machineagent_systemd }}.service"
    owner: tomcat
    group: tomcat
    mode: '0777'
  become: true  

- name: Enable and Start Machine Agent Service
  service: 
    name: "{{ machineagent_systemd }}"
    enabled: true 
    state: started
  become: yes    
    
