---
- include_vars: java-agent-vars.yml

- name: Create a directory if it does not exist
  file:
    path: "{{ binary_path }}"
    state: directory
    owner: tomcat
    group: tomcat
    mode: '0777'

- name: tar extract app agent binaries
  unarchive:
    src: "/home/tomcat/{{ zip_file }}"
    dest: "{{ binary_path }}"
    remote_src: yes

- name: Template config file to install folder
  template:
    src: "{{ controller_xml }}.j2"
    dest: "{{ binary_path }}/conf/{{ controller_xml }}"
    owner: tomcat
    group: tomcat
    mode: '0777'