---
- include_vars: java-analyticsagent-vars.yml

- name: Template analytics properties file for install
  template:
    src: "{{ analytics_properties }}.j2"
    dest: "{{ binary_path }}/monitors/analytics-agent/conf/{{ analytics_properties }}"
  become: yes
  register: result


- name: Restart Machine Agent Service
  service: 
    name: "{{ machineagent_systemd }}" 
    state: restarted
  become: yes    
    
